SELECT
    t.TABLE_NAME,
    COUNT(c.COLUMN_NAME) AS ColumnCount
FROM
    INFORMATION_SCHEMA.TABLES t
    INNER JOIN INFORMATION_SCHEMA.COLUMNS c ON t.TABLE_NAME = c.TABLE_NAME
    AND t.TABLE_SCHEMA = c.TABLE_SCHEMA
WHERE
    t.TABLE_TYPE = 'BASE TABLE'
GROUP BY
    t.TABLE_NAME
ORDER BY
    t.TABLE_NAME;